// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oipvtfamhmrdvmrwsaci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pcHZ0ZmFtaG1yZHZtcndzYWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTM0MjQsImV4cCI6MjA2NTQ2OTQyNH0.O1oDZkw50qYXzEh7RiEah1amoJCTzdPqhkLxfAlobuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);